version: "3"
services:

  # Fronnted
  go-indexing:
    build: api-crud-complete-chi
    hostname: go-indexing
    container_name: go-indexing
    environment:
      PORT: 0.0.0.0:8080
      CORS_ALLOW_ORIGINS: "*"
      CORS_ALLOW_HEADERS: Content-Type,Authorization
      CORS_ALLOW_METHODS: GET,POST,PUT,DELETE,OPTIONS
      CORS_ALLOW_CREDENTIALS: "true"
      CORS_EXPOSE_HEADERS: Content-Type,Authorization
      USER_PASSWORD: 123456
      USER_EMAIL: admin@localhost
      JWT_SECRET: as7dya87syd8as7dy87
      URL_BD_ZINSEARCH: http://host.docker.internal:4080/
      NFS_PATH: "/home/"
      NOMBRE: DIEGOLS
      ROUTE_TEMP_FILES: "/temp/"
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/linux/Documentos/:/home/
